#-------------#
# Import Vars #
#-------------#
Import('*')

#---------#
# Sources #
#---------#
src = Split("""body.png
		body00.png
               body01.png
               body02.png
               body03.png
               body04.png
               body05.png
               body06.png
               body07.png
               glass.png
	       shadow.png
               wheel_front.png
               wheel_rear.png""")

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)
env.Distribute (bin_dir, src)

#--------------------#
# Install data files #
#--------------------#
install = env.Install(Dir(env.subst('$data_directory/cars/CS/textures')), src)
env.Alias('install', install)
