#-------------#
# Import Vars #
#-------------#
Import('*')

#---------#
# Sources #
#---------#
src = Split("""crash.wav
               tire_squeal.wav
               bump_front.wav
               bump_rear.wav
               wind.wav""")

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)
env.Distribute (bin_dir, src)

#--------------------#
# Install data files #
#--------------------#
install = env.Install(Dir(env.subst('$data_directory/sounds')), src)
env.Alias('install', install)
