import glob.glob
#-------------#
# Import Vars #
#-------------#
Import('*')

#---------#
# Sources #
#---------#
src = glob('*.glsl')

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)
env.Distribute (bin_dir, src)

#--------------------#
# Install data files #
#--------------------#
install = env.Install(Dir(env.subst('$data_directory/shaders/hblur_rect')), src)
env.Alias('install', install)

#----------------#
# Subdirectories #
#----------------#
Export(['env', 'src_dir', 'bin_dir'])

