#-------------#
# Import Vars #
#-------------#
Import('*')

#---------#
# Sources #
#---------#
src = Split("""carbon-metallic1""")

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)
env.Distribute (bin_dir, src)

#--------------------#
# Install data files #
#--------------------#
Export(['env', 'src_dir', 'bin_dir'])
install = env.Install(Dir(env.subst('$data_directory/carparts/brake')), src)
env.Alias('install', install)
