#-------------#
# Import Vars #
#-------------#
Import('*')

import glob

#---------#
# Sources #
#---------#
src = glob.glob("*.png")

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)
env.Distribute (bin_dir, src)

#--------------------#
# Install data files #
#--------------------#
install = env.Install(Dir(env.subst('$data_directory/cars/CO/textures')), src)
env.Alias('install', install)
